#!/bin/bash
# Safari Extension Build Script
# 
# This script builds the Harbor extension for Safari, including the
# harbor-bridge native messaging binary, and packages everything
# into a macOS app bundle using Xcode.
#
# Prerequisites:
# - Xcode installed (13.0+)
# - Rust toolchain (for harbor-bridge)
# - Node.js and npm (for extension)
# - Apple Developer account (for code signing, optional for dev)
#
# Usage:
#   ./build.sh           # Build for development
#   ./build.sh release   # Build release archive
#   ./build.sh setup     # Just run initial setup

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
EXTENSION_DIR="$PROJECT_ROOT/extension"
BRIDGE_DIR="$PROJECT_ROOT/bridge-rs"
OUTPUT_DIR="$SCRIPT_DIR/build"
XCODE_PROJECT="$SCRIPT_DIR/Harbor/Harbor.xcodeproj"

# Parse arguments
BUILD_MODE="${1:-debug}"

echo "=== Harbor Safari Extension Build ==="
echo ""

# Check for Xcode
if ! command -v xcodebuild &> /dev/null; then
    echo "Error: Xcode command line tools not found."
    echo "Install with: xcode-select --install"
    exit 1
fi

# Check if project exists, run setup if not
if [ ! -d "$XCODE_PROJECT" ]; then
    echo "Xcode project not found. Running setup..."
    echo ""
    "$SCRIPT_DIR/setup-xcode-project.sh"
    echo ""
    echo "Setup complete. Please configure signing in Xcode, then run this script again."
    exit 0
fi

# Handle setup-only mode
if [ "$BUILD_MODE" = "setup" ]; then
    "$SCRIPT_DIR/setup-xcode-project.sh"
    exit 0
fi

# Step 1: Build harbor-bridge
echo "Step 1: Building harbor-bridge..."
cd "$BRIDGE_DIR"

if ! command -v cargo &> /dev/null; then
    echo "Error: Rust/Cargo not found."
    echo "Install from: https://rustup.rs"
    exit 1
fi

cargo build --release
BRIDGE_BINARY="$BRIDGE_DIR/target/release/harbor-bridge"

if [ ! -f "$BRIDGE_BINARY" ]; then
    echo "Error: harbor-bridge binary not found at $BRIDGE_BINARY"
    exit 1
fi
echo "  Built: $BRIDGE_BINARY"

# Step 2: Build the extension for Safari
echo ""
echo "Step 2: Building extension for Safari..."
cd "$EXTENSION_DIR"

if [ ! -d "node_modules" ]; then
    echo "  Installing dependencies..."
    npm install
fi

npm run build:safari
echo "  Built extension in $EXTENSION_DIR/dist-safari"

# Step 3: Update extension files in Xcode project
echo ""
echo "Step 3: Syncing extension files to Xcode project..."

# Safari dist already contains everything in the right structure
SAFARI_DIST="$EXTENSION_DIR/dist-safari"
RESOURCES_DIR="$SCRIPT_DIR/Harbor/Harbor Extension/Resources"

if [ -d "$RESOURCES_DIR" ]; then
    # Clear old resources and sync from Safari dist
    # Keep _locales if it exists (generated by converter)
    rm -rf "$RESOURCES_DIR/manifest.json" "$RESOURCES_DIR/assets" "$RESOURCES_DIR/demo" \
           "$RESOURCES_DIR/bundled" "$RESOURCES_DIR"/*.js "$RESOURCES_DIR"/*.html \
           "$RESOURCES_DIR"/*.css "$RESOURCES_DIR/js-runtime"
    
    # Copy all from dist-safari (already has correct structure)
    cp -r "$SAFARI_DIST/"* "$RESOURCES_DIR/"
    
    echo "  Synced to $RESOURCES_DIR"
else
    echo "Warning: Resources directory not found at $RESOURCES_DIR"
    echo "  You may need to regenerate the Xcode project with: ./setup-xcode-project.sh"
fi

# Step 4: Build with Xcode
echo ""
echo "Step 4: Building with Xcode..."

mkdir -p "$OUTPUT_DIR"

if [ "$BUILD_MODE" = "release" ]; then
    echo "  Building release archive..."
    xcodebuild -project "$XCODE_PROJECT" \
        -scheme "Harbor (macOS)" \
        -configuration Release \
        -archivePath "$OUTPUT_DIR/Harbor.xcarchive" \
        archive
    
    echo ""
    echo "=== Release Build Complete ==="
    echo ""
    echo "Archive created at: $OUTPUT_DIR/Harbor.xcarchive"
    echo ""
    echo "To export for distribution:"
    echo "  xcodebuild -exportArchive \\"
    echo "    -archivePath $OUTPUT_DIR/Harbor.xcarchive \\"
    echo "    -exportPath $OUTPUT_DIR \\"
    echo "    -exportOptionsPlist exportOptions.plist"
    echo ""
    echo "For App Store distribution, use Xcode Organizer."
else
    echo "  Building for development..."
    xcodebuild -project "$XCODE_PROJECT" \
        -scheme "Harbor (macOS)" \
        -configuration Debug \
        build \
        SYMROOT="$OUTPUT_DIR"
    
    # Copy harbor-bridge to the built app
    APP_PATH="$OUTPUT_DIR/Debug/Harbor.app"
    if [ -d "$APP_PATH" ]; then
        DEST_BINARY="$APP_PATH/Contents/MacOS/harbor-bridge"
        cp "$BRIDGE_BINARY" "$DEST_BINARY"
        chmod +x "$DEST_BINARY"
        echo "  Copied harbor-bridge to app bundle"
    fi
    
    echo ""
    echo "=== Development Build Complete ==="
    echo ""
    echo "App built at: $APP_PATH"
    echo ""
    echo "To test:"
    echo "  1. Open the app: open \"$APP_PATH\""
    echo "  2. Enable in Safari: Safari → Settings → Extensions → Harbor"
    echo ""
    echo "For unsigned extensions, first enable:"
    echo "  Safari → Develop → Allow Unsigned Extensions"
    echo ""
    echo "To see extension logs:"
    echo "  Safari → Develop → Web Extension Background Content"
fi
